#ifndef BLOCKSIZEDEFINER_H
#define BLOCKSIZEDEFINER_H


#define NN 75
#define NM 75
#define NL 75
#define LAYER NN*NM
#define NODES NN*NM*NL
#define LAYERS_PER_THREAD ((int)(NL/THREADS))
#define BLOCKSIZE LAYER*LAYERS_PER_THREAD

#endif
