#ifndef BLOCKSIZEDEFINER_H
#define BLOCKSIZEDEFINER_H


#define NN 30
#define NM 30
#define NL 30
#define LAYER NN*NM
#define NODES NN*NM*NL
#define LAYERS_PER_THREAD ((int)(NL/THREADS))
#define BLOCKSIZE LAYER*LAYERS_PER_THREAD

#endif
