#ifndef BLOCKSIZEDEFINER_H
#define BLOCKSIZEDEFINER_H


#define NN 128
#define NM 128
#define NL 128
#define LAYER NN*NM
#define NODES NN*NM*NL
#define LAYERS_PER_THREAD ((int)(NL/THREADS))
#define BLOCKSIZE LAYER*LAYERS_PER_THREAD

#endif
